[application]

sub-package = "app"

[web.app]

# HTML title tag content
title = "vox-fila"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []

[bundle]
category = "Music"
short_description = "App for KJs who don't want to rely on any particular software"
long_description = "App for easier handling of karaoke queues without relying on any particular karaoke software"
