services:
  postgres:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 42222:5432
    environment:
      POSTGRES_PASSWORD: postgres
    restart: always
    networks:
      - default
  pg_admin:
    image: dpage/pgadmin4:latest
    ports:
      - 5090:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: always
    volumes:
      - ./pgadmin/servers.json:/pgadmin4/servers.json
    networks:
      - default
volumes:
  db-data:
networks:
  default:
    driver: bridge
