services:
  postgres:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 4222:5432
    environment:
      POSTGRES_PASSWORD: postgres
    restart: always
  pg_admin:
    image: dpage/pgadmin4:latest
    ports:
      - 5060:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: always
volumes:
  db-data:
