# Default configuration for rustfmt
# See https://rust-lang.github.io/rustfmt/ for more details

edition = "2021"
max_width = 100
tab_spaces = 4
newline_style = "Auto"
use_field_init_shorthand = true
